artifacts_root: artifacts

data_ingestion:
  root_directory: artifacts/data_ingestion
  # getting dataset from raw github
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/refs/heads/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir:  artifacts/data_ingestion