# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hymenoptera

on:
  push:
    branches:
      - torchcode
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://devmlopsregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ae23622767684d4995aa08139ff4a4f6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e5a85dd48c884157abbca6cc4c2a5c81 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: devmlopsregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae23622767684d4995aa08139ff4a4f6 }}/hymenoptera:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hymenoptera'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c1e1e7215fca4e7ea67306f1c11fd200 }}
        images: 'devmlopsregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ae23622767684d4995aa08139ff4a4f6 }}/hymenoptera:${{ github.sha }}'